CREATE TABLE IF NOT EXISTS rate_limits (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  minute_count INTEGER NOT NULL DEFAULT 0,
  minute_reset TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  day_count INTEGER NOT NULL DEFAULT 0,
  day_tokens INTEGER NOT NULL DEFAULT 0,
  day_reset TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
